import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"; // Import React Toastify CSS
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Import ToastContainer from react-toastify */}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLos
          pauseOnHover
          theme="dark"
        />
        {children}
      </body>
    </html>
  );
}
